{**
 * Flickr - feature-based reranking
 * MI-VMW at CZECH TECHNICAL UNIVERSITY IN PRAGUE
 *
 * @copyright  Copyright (c) 2010
 * @package    VMW
 * @author     Jaroslav Líbal, Martin Venuš
 *
 *}
{block header}
Parametry vyhledávání
{/block}
{block content}
{widget mainForm}
<strong>Poznámka:</strong> Flickr API vrací v některých případech fotografie v nedostatečném rozlišení. Takové fotografie nelze použít pro barevnou analýzu a nejsou tak zobrazovány ve výsledcích vyhledávání. Je tedy možné, že při zadání požadavku na vyhledání 20 fotografií bude výsledek obsahovat méně fotografií.
{/block}