{**
 * Flickr - feature-based reranking
 * MI-VMW at CZECH TECHNICAL UNIVERSITY IN PRAGUE
 *
 * @copyright  Copyright (c) 2010
 * @package    VMW
 * @author     Jaroslav Líbal, Martin Venuš
 *
 * @param string   $basePath web base path
 * @param array    $flashes  flash messages
 *}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>VMW</title>
        <link rel="stylesheet" type="text/css" href="{$baseUri}style.css" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
        <script type="text/javascript" src="{$baseUri}fancybox/jquery.fancybox-1.3.4.pack.js"></script>
        <link rel="stylesheet" href="{$baseUri}fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />

        <script type="text/javascript">

            <!-- <![CDATA[
            $(document).ready(function()
            {

                $("a[rel*=lightbox]").fancybox();

            });
            //]]> -->
        </script>


    </head>
    <body>
        <div id="top_menu">
            <ul class="menu">
                <li><a href="{link Homepage:default}" class="nav">Úvodní stránka</a></li>
            </ul>
        </div>
        <div id="main_content">
            <div id="top_banner">
                <a href="{link Homepage:default}"><img src="{$baseUri}images/logo.jpg" width="230" height="130" alt="home" title="logo" border="0" class="logo" /></a>
            </div>

            <div id="page_content">

                <div class="title">
                    {include #header}
                </div>
                
                <div class="content_text">

                    {foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

                    {include #content}

                </div>
            </div>
        </div>

        <div id="footer">
            <div id="footer_content">
                <div id="copyrights">
                    Martin Venuš & Jaroslav Líbal, 2010
                </div>

                <div id="madeby">
                    <a href="http://www.csscreme.com"><img src="images/csscreme_link.jpg" width="125" height="40"  border="0" alt="csscreme" title="csscreme"/></a>
                </div>
            </div>
        </div>

    </body>
</html>

