<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>VMW</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
    </head>
    <body>
        <div id="top_menu">
            <ul class="menu">
                <li><a href="index.html" class="nav">home</a></li>
            </ul>
        </div>
        <div id="main_content">
            <div id="top_banner">
                <a href="index.html"><img src="images/logo.jpg" width="230" height="130" alt="home" title="logo" border="0" class="logo" /></a>
            </div>

            <div id="page_content">

                <div class="title">
                    {include #header}
                </div>
                <div class="content_text">

                    {foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

                    {include #content}


                </div>



            </div>

        </div>

        <div id="footer">
            <div id="footer_content">
                <div id="copyrights">
                    Quartz Solution.&copy; All Rights Reserved 2007
                </div>

                <div id="madeby">
                    <a href="http://www.csscreme.com"><img src="images/csscreme_link.jpg" width="125" height="40"  border="0" alt="csscreme" title="csscreme"/></a>
                </div>
            </div>

        </div>

    </body>
</html>

